"""add_indices_to_frequently_filtered_columns

Revision ID: 19f3576b5827
Revises: 5eac3d59b9db
Create Date: 2026-03-03 21:12:09.901614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f3576b5827'
down_revision = '5eac3d59b9db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prenominas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prenominas_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_prenominas_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_prenominas_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prestamos_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_prestamos_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('registros_diarios_horas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_registros_diarios_horas_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_diarios_horas_reporte_id'), ['reporte_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_registros_diarios_horas_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('reportes_semanales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reportes_semanales_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_reportes_semanales_fecha_inicio_semana'), ['fecha_inicio_semana'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reportes_semanales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reportes_semanales_fecha_inicio_semana'))
        batch_op.drop_index(batch_op.f('ix_reportes_semanales_estado'))

    with op.batch_alter_table('registros_diarios_horas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_registros_diarios_horas_trabajador_id'))
        batch_op.drop_index(batch_op.f('ix_registros_diarios_horas_reporte_id'))
        batch_op.drop_index(batch_op.f('ix_registros_diarios_horas_fecha'))

    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prestamos_trabajador_id'))
        batch_op.drop_index(batch_op.f('ix_prestamos_estado'))

    with op.batch_alter_table('prenominas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prenominas_trabajador_id'))
        batch_op.drop_index(batch_op.f('ix_prenominas_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_prenominas_estado'))

    # ### end Alembic commands ###
