"""Add DescuentoPrenomina DepositoExtra and expand Prestamo

Revision ID: 3f1a4017449e
Revises: 43225a3b5ecb
Create Date: 2026-02-25 23:48:30.011647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f1a4017449e'
down_revision = '43225a3b5ecb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('depositos_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenomina_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('concepto', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prenomina_id'], ['prenominas.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('descuentos_prenomina',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prenomina_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('concepto', sa.String(length=250), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_incidencia', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['prenomina_id'], ['prenominas.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motivo', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('frecuencia', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('estado', sa.String(length=20), nullable=True))

    with op.batch_alter_table('registros_diarios_horas', schema=None) as batch_op:
        batch_op.drop_column('detalles_incidencia')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_diarios_horas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detalles_incidencia', sa.TEXT(), autoincrement=False, nullable=True))

    with op.batch_alter_table('prestamos', schema=None) as batch_op:
        batch_op.drop_column('estado')
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('frecuencia')
        batch_op.drop_column('motivo')

    op.drop_table('descuentos_prenomina')
    op.drop_table('depositos_extra')
    # ### end Alembic commands ###
