"""Add tipo_nomina a trabajadores

Revision ID: 43225a3b5ecb
Revises: c7cad5532705
Create Date: 2026-02-24 16:14:32.980783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43225a3b5ecb'
down_revision = 'c7cad5532705'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_nomina', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_column('tipo_nomina')

    # ### end Alembic commands ###
