"""init workers

Revision ID: 453bd924fe1d
Revises: 
Create Date: 2026-02-19 23:37:21.698764

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '453bd924fe1d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proyectos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_proyecto', sa.String(length=100), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_proyecto')
    )
    op.create_table('trabajadores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_empleado', sa.String(length=50), nullable=False),
    sa.Column('nombre_apellidos', sa.String(length=250), nullable=False),
    sa.Column('nombre', sa.String(length=250), nullable=False),
    sa.Column('tipo_mov', sa.String(length=100), nullable=True),
    sa.Column('tipo_cont', sa.String(length=100), nullable=True),
    sa.Column('area', sa.String(length=150), nullable=True),
    sa.Column('puesto', sa.String(length=150), nullable=True),
    sa.Column('fecha_ingreso', sa.Date(), nullable=True),
    sa.Column('tipo_jornada', sa.String(length=100), nullable=True),
    sa.Column('descripcion_servicio', sa.Text(), nullable=True),
    sa.Column('inicio', sa.Date(), nullable=True),
    sa.Column('termino_prueba', sa.Date(), nullable=True),
    sa.Column('fecha_baja', sa.Date(), nullable=True),
    sa.Column('curp', sa.String(length=18), nullable=True),
    sa.Column('largo_curp', sa.Integer(), nullable=True),
    sa.Column('rfc', sa.String(length=13), nullable=True),
    sa.Column('largo_rfc', sa.Integer(), nullable=True),
    sa.Column('nss', sa.String(length=20), nullable=True),
    sa.Column('largo_nss', sa.Integer(), nullable=True),
    sa.Column('domicilio', sa.Text(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('letra_fecha_nac', sa.String(length=50), nullable=True),
    sa.Column('edad', sa.Integer(), nullable=True),
    sa.Column('sexo', sa.String(length=20), nullable=True),
    sa.Column('nacionalidad', sa.String(length=100), nullable=True),
    sa.Column('estado_civil', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('celular', sa.String(length=20), nullable=True),
    sa.Column('tipo_sangre', sa.String(length=10), nullable=True),
    sa.Column('alergias', sa.Text(), nullable=True),
    sa.Column('contacto_emergencia', sa.String(length=200), nullable=True),
    sa.Column('numero_contacto_emerg', sa.String(length=20), nullable=True),
    sa.Column('lentes', sa.String(length=20), nullable=True),
    sa.Column('licencia_conducir', sa.String(length=50), nullable=True),
    sa.Column('estatura', sa.String(length=20), nullable=True),
    sa.Column('sb', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('sdi', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('letra', sa.String(length=10), nullable=True),
    sa.Column('salario_real_pactado_x_sem', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('hr_extra', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('infonavit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ajuste_inbursa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('caja_ahorro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('viaticos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pagos_efectivo', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('folio_mov_idse', sa.String(length=100), nullable=True),
    sa.Column('tipo_pago', sa.String(length=100), nullable=True),
    sa.Column('no_proyecto', sa.String(length=100), nullable=True),
    sa.Column('coord_a_cargo', sa.String(length=150), nullable=True),
    sa.Column('ubicacion_actual', sa.String(length=150), nullable=True),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('caet', sa.String(length=100), nullable=True),
    sa.Column('stellantis', sa.String(length=100), nullable=True),
    sa.Column('audi', sa.String(length=100), nullable=True),
    sa.Column('bmw', sa.String(length=100), nullable=True),
    sa.Column('axalta', sa.String(length=100), nullable=True),
    sa.Column('volvo', sa.String(length=100), nullable=True),
    sa.Column('dtna', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('no_empleado')
    )
    op.create_table('prestamos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('monto_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('plazo_semanas', sa.Integer(), nullable=False),
    sa.Column('descuento_semanal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('monto_restante', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reportes_semanales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio_semana', sa.Date(), nullable=False),
    sa.Column('fecha_fin_semana', sa.Date(), nullable=False),
    sa.Column('proyecto_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['proyecto_id'], ['proyectos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prenominas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporte_semanal_id', sa.Integer(), nullable=True),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('salario_base', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pago_horas_extras', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pago_viaticos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pago_festivos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('depositos_otros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('depositos_prestamos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento_infonavit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ajuste_inbursa', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuentos_otros', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento_prestamos', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('descuento_incidencias', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recuperacion_manual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_percepciones', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_deducciones', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_a_pagar', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('tipo_pago', sa.String(length=50), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['reporte_semanal_id'], ['reportes_semanales.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_diarios_horas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reporte_id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('hora_entrada', sa.Time(), nullable=True),
    sa.Column('hora_salida', sa.Time(), nullable=True),
    sa.Column('tomo_comida', sa.Boolean(), nullable=True),
    sa.Column('incidencia', sa.String(length=100), nullable=True),
    sa.Column('tipo_nomina', sa.String(length=50), nullable=True),
    sa.Column('horas_productivas', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['reporte_id'], ['reportes_semanales.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registros_diarios_horas')
    op.drop_table('prenominas')
    op.drop_table('reportes_semanales')
    op.drop_table('prestamos')
    op.drop_table('trabajadores')
    op.drop_table('proyectos')
    # ### end Alembic commands ###
