"""Add CredencialPlanta tracking

Revision ID: 4911fa6d1b22
Revises: 453bd924fe1d
Create Date: 2026-02-21 15:39:36.711821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4911fa6d1b22'
down_revision = '453bd924fe1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credenciales_plantas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('planta', sa.String(length=100), nullable=False),
    sa.Column('credencial_id', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_column('audi')
        batch_op.drop_column('volvo')
        batch_op.drop_column('bmw')
        batch_op.drop_column('caet')
        batch_op.drop_column('dtna')
        batch_op.drop_column('axalta')
        batch_op.drop_column('stellantis')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stellantis', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('axalta', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('dtna', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('caet', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('bmw', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('volvo', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('audi', sa.VARCHAR(length=100), autoincrement=False, nullable=True))

    op.drop_table('credenciales_plantas')
    # ### end Alembic commands ###
