"""add tipo_documento to documentos_trabajador

Revision ID: 4f5bae75a729
Revises: 8656cf229bbb
Create Date: 2026-03-09 15:44:32.332258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5bae75a729'
down_revision = '8656cf229bbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_documento', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_trabajador', schema=None) as batch_op:
        batch_op.drop_column('tipo_documento')

    # ### end Alembic commands ###
