"""Inventario

Revision ID: 5838d810af16
Revises: a9da82baeee9
Create Date: 2026-04-08 05:49:43.747461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5838d810af16'
down_revision = 'a9da82baeee9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('almacenes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('ubicacion', sa.String(length=250), nullable=True),
    sa.Column('qr_code', sa.String(length=100), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('almacenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_almacenes_qr_code'), ['qr_code'], unique=True)

    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=250), nullable=False),
    sa.Column('categoria', sa.String(length=100), nullable=False),
    sa.Column('unidad', sa.String(length=50), nullable=False),
    sa.Column('stock_actual', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock_minimo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_productos_activo'), ['activo'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_productos_codigo'), ['codigo'], unique=True)

    op.create_table('solicitudes_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitante_id', sa.Integer(), nullable=False),
    sa.Column('proyecto', sa.String(length=200), nullable=True),
    sa.Column('estatus', sa.String(length=50), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_cierre', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['solicitante_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_material', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_material_estatus'), ['estatus'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_material_fecha_creacion'), ['fecha_creacion'], unique=False)
        batch_op.create_index(batch_op.f('ix_solicitudes_material_solicitante_id'), ['solicitante_id'], unique=False)

    op.create_table('movimientos_inventario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('almacen_origen_id', sa.Integer(), nullable=True),
    sa.Column('almacen_destino_id', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('motivo', sa.String(length=250), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['almacen_destino_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['almacen_origen_id'], ['almacenes.id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_almacen_destino_id'), ['almacen_destino_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_almacen_origen_id'), ['almacen_origen_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_fecha'), ['fecha'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_producto_id'), ['producto_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_movimientos_inventario_tipo'), ['tipo'], unique=False)

    op.create_table('solicitudes_material_detalle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('solicitud_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad_solicitada', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('cantidad_aprobada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cantidad_entregada', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['producto_id'], ['productos.id'], ),
    sa.ForeignKeyConstraint(['solicitud_id'], ['solicitudes_material.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('solicitudes_material_detalle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_solicitudes_material_detalle_solicitud_id'), ['solicitud_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitudes_material_detalle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_material_detalle_solicitud_id'))

    op.drop_table('solicitudes_material_detalle')
    with op.batch_alter_table('movimientos_inventario', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_tipo'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_producto_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_fecha'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_almacen_origen_id'))
        batch_op.drop_index(batch_op.f('ix_movimientos_inventario_almacen_destino_id'))

    op.drop_table('movimientos_inventario')
    with op.batch_alter_table('solicitudes_material', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_solicitudes_material_solicitante_id'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_material_fecha_creacion'))
        batch_op.drop_index(batch_op.f('ix_solicitudes_material_estatus'))

    op.drop_table('solicitudes_material')
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_productos_codigo'))
        batch_op.drop_index(batch_op.f('ix_productos_categoria'))
        batch_op.drop_index(batch_op.f('ix_productos_activo'))

    op.drop_table('productos')
    with op.batch_alter_table('almacenes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_almacenes_qr_code'))

    op.drop_table('almacenes')
    # ### end Alembic commands ###
