"""Agregar dias festivos

Revision ID: 5eac3d59b9db
Revises: a2f48d521b12
Create Date: 2026-03-03 20:21:04.856722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5eac3d59b9db'
down_revision = 'a2f48d521b12'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registros_diarios_horas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aplica_viaticos', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('aplica_dia_festivo', sa.Boolean(), nullable=True))

    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pago_dia_festivo', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_column('pago_dia_festivo')

    with op.batch_alter_table('registros_diarios_horas', schema=None) as batch_op:
        batch_op.drop_column('aplica_dia_festivo')
        batch_op.drop_column('aplica_viaticos')

    # ### end Alembic commands ###
