"""Add ubicacion_estado

Revision ID: 60acfa1c0cad
Revises: 19f3576b5827
Create Date: 2026-03-03 22:07:02.095697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60acfa1c0cad'
down_revision = '19f3576b5827'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ubicacion_estado', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_column('ubicacion_estado')

    # ### end Alembic commands ###
