"""Agregar fechas de caducidad a documentos

Revision ID: 6857320823ab
Revises: d9e3f4a5b6c7
Create Date: 2026-03-06 18:58:06.360093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6857320823ab'
down_revision = 'd9e3f4a5b6c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ajuste_trabajadores_periodo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ajuste_tp_periodo_id'))
        batch_op.drop_index(batch_op.f('ix_ajuste_tp_trabajador_id'))
        batch_op.create_index(batch_op.f('ix_ajuste_trabajadores_periodo_periodo_id'), ['periodo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ajuste_trabajadores_periodo_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('documentos_trabajador', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_fin', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('documentos_trabajador', schema=None) as batch_op:
        batch_op.drop_column('fecha_fin')
        batch_op.drop_column('fecha_inicio')

    with op.batch_alter_table('ajuste_trabajadores_periodo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ajuste_trabajadores_periodo_trabajador_id'))
        batch_op.drop_index(batch_op.f('ix_ajuste_trabajadores_periodo_periodo_id'))
        batch_op.create_index(batch_op.f('ix_ajuste_tp_trabajador_id'), ['trabajador_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ajuste_tp_periodo_id'), ['periodo_id'], unique=False)

    # ### end Alembic commands ###
