"""Agregar fecha de caducidad a credenciales

Revision ID: 6fb90b5cd846
Revises: 6857320823ab
Create Date: 2026-03-06 19:04:08.220118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fb90b5cd846'
down_revision = '6857320823ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credenciales_plantas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_caducidad', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credenciales_plantas', schema=None) as batch_op:
        batch_op.drop_column('fecha_caducidad')

    # ### end Alembic commands ###
