"""Agregar modelos de ausencias y vacaciones

Revision ID: 8656cf229bbb
Revises: 6fb90b5cd846
Create Date: 2026-03-08 00:11:32.690980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8656cf229bbb'
down_revision = '6fb90b5cd846'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ausencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=False),
    sa.Column('tipo_ausencia', sa.String(length=50), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('dias_solicitados', sa.Integer(), nullable=True),
    sa.Column('motivo', sa.Text(), nullable=True),
    sa.Column('creado_por_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creado_por_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ausencias', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ausencias_fecha_fin'), ['fecha_fin'], unique=False)
        batch_op.create_index(batch_op.f('ix_ausencias_fecha_inicio'), ['fecha_inicio'], unique=False)
        batch_op.create_index(batch_op.f('ix_ausencias_trabajador_id'), ['trabajador_id'], unique=False)

    op.create_table('saldo_vacaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trabajador_id', sa.Integer(), nullable=False),
    sa.Column('dias_totales_asignados', sa.Integer(), nullable=False),
    sa.Column('dias_disfrutados', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trabajador_id'], ['trabajadores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('saldo_vacaciones', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saldo_vacaciones_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proyectos_activo'), ['activo'], unique=False)

    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_trabajadores_activo'), ['activo'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabajadores_activo'))

    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proyectos_activo'))

    with op.batch_alter_table('saldo_vacaciones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saldo_vacaciones_trabajador_id'))

    op.drop_table('saldo_vacaciones')
    with op.batch_alter_table('ausencias', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ausencias_trabajador_id'))
        batch_op.drop_index(batch_op.f('ix_ausencias_fecha_inicio'))
        batch_op.drop_index(batch_op.f('ix_ausencias_fecha_fin'))

    op.drop_table('ausencias')
    # ### end Alembic commands ###
