"""Add enfermedades_cronicas and parentesco_contacto

Revision ID: a2f48d521b12
Revises: 3f1a4017449e
Create Date: 2026-02-27 22:20:25.833257

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f48d521b12'
down_revision = '3f1a4017449e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('enfermedades_cronicas', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('parentesco_contacto', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_column('parentesco_contacto')
        batch_op.drop_column('enfermedades_cronicas')

    # ### end Alembic commands ###
