"""add_performance_indexes2

Revision ID: a9da82baeee9
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 17:35:52.833525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9da82baeee9'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credenciales_plantas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credenciales_plantas_trabajador'))
        batch_op.create_index(batch_op.f('ix_credenciales_plantas_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('depositos_extra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depositos_extra_prenomina'))
        batch_op.create_index(batch_op.f('ix_depositos_extra_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('descuentos_prenomina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_descuentos_prenomina_prenomina'))
        batch_op.create_index(batch_op.f('ix_descuentos_prenomina_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('documentos_trabajador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_trabajador_tipo'))
        batch_op.create_index(batch_op.f('ix_documentos_trabajador_trabajador_id'), ['trabajador_id'], unique=False)

    with op.batch_alter_table('prenominas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prenominas_fecha_estado'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prenominas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prenominas_fecha_estado'), ['fecha_inicio', 'estado'], unique=False)

    with op.batch_alter_table('documentos_trabajador', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documentos_trabajador_trabajador_id'))
        batch_op.create_index(batch_op.f('ix_documentos_trabajador_tipo'), ['trabajador_id', 'tipo_documento'], unique=False)

    with op.batch_alter_table('descuentos_prenomina', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_descuentos_prenomina_trabajador_id'))
        batch_op.create_index(batch_op.f('ix_descuentos_prenomina_prenomina'), ['prenomina_id'], unique=False)

    with op.batch_alter_table('depositos_extra', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_depositos_extra_trabajador_id'))
        batch_op.create_index(batch_op.f('ix_depositos_extra_prenomina'), ['prenomina_id'], unique=False)

    with op.batch_alter_table('credenciales_plantas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credenciales_plantas_trabajador_id'))
        batch_op.create_index(batch_op.f('ix_credenciales_plantas_trabajador'), ['trabajador_id'], unique=False)

    # ### end Alembic commands ###
