"""Rename supervisor to coordinador

Revision ID: c7cad5532705
Revises: cc5aa79a3ea6
Create Date: 2026-02-23 21:23:09.180312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cad5532705'
down_revision = 'cc5aa79a3ea6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coordinador_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint(batch_op.f('proyectos_supervisor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['coordinador_id'], ['id'])
        batch_op.drop_column('supervisor_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supervisor_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proyectos_supervisor_id_fkey'), 'users', ['supervisor_id'], ['id'])
        batch_op.drop_column('coordinador_id')

    # ### end Alembic commands ###
