"""change_supervisor_to_user

Revision ID: cc5aa79a3ea6
Revises: 9261526076a9
Create Date: 2026-02-23 16:53:18.973795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc5aa79a3ea6'
down_revision = '9261526076a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('proyectos_supervisor_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['supervisor_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proyectos', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('proyectos_supervisor_id_fkey'), 'trabajadores', ['supervisor_id'], ['id'])

    # ### end Alembic commands ###
