"""add qr_code to trabajadores

Revision ID: d1b22089662b
Revises: b5a9661a7166
Create Date: 2026-05-09 14:38:24.223413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1b22089662b'
down_revision = 'b5a9661a7166'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('refresh_tokens_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])

    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code', sa.String(length=100), nullable=True))
        batch_op.create_index(batch_op.f('ix_trabajadores_qr_code'), ['qr_code'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('trabajadores', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_trabajadores_qr_code'))
        batch_op.drop_column('qr_code')

    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('refresh_tokens_user_id_fkey'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
